## Numpy
library for scientific computing it provides support for arrays,metrics along with mathematical function

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)
arr1.reshape(4,1)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


array([[1],
       [2],
       [3],
       [4]])

In [5]:
np.arange(0,10,2).reshape(5,1)
# np.ones((3,4))
np.eye(3).astype(int)  ## identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
## combining array
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
print("Transpose of C:",c.T)
print(np.vstack((a,b)))
# print(np.hstack((a,b)))
# print(b.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [37]:
np.random.rand(2,3)

array([[0.68610052, 0.21757005, 0.55738793],
       [0.82965517, 0.29535761, 0.4691363 ]])

In [15]:
## Attributes of Numpy

arr = np.array([[1,2,3], [4,5,6]])

print("Arr: ",arr)
print("Arr shape: ",arr.shape)
print("dimension: ",arr.ndim)
print("size(no. of element): ",arr.size)
print("Data type: ",arr.dtype)
print("item size(in bytes): ",arr.itemsize)

Arr:  [[1 2 3]
 [4 5 6]]
Arr shape:  (2, 3)
dimension:  2
size(no. of element):  6
Data type:  int64
item size(in bytes):  8


In [16]:
## vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ", arr1+arr2)
print("Subtraction: ", arr1-arr2)
print("Multiplication: ", arr1*arr2)
print("Division: ", arr1/arr2)


Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
arr = np.array([1,2,3,4])

print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.cbrt(arr))

[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[1.         1.25992105 1.44224957 1.58740105]


In [ ]:
# Array slicing and indxing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr[0,0])
print(arr[1:,2:])  # arr[row_start:row_end, col_start:col_end]
print(arr[0:2,2:])
arr[0,0] = 100
print(arr)
arr[1:] = 0
print(arr)

1
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  0   0   0   0]
 [  0   0   0   0]]


In [35]:
# statistical concepts

data = np.array([1,2,3,4,5])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
normalized_data = (data-mean)/std_dev
variance = np.var(data)

print("Mean:",mean)
print("Median:",median)
print("standard deviation:",std_dev)
print("Normalized data:",normalized_data)
print("Variance:",variance)


Mean: 3.0
Median: 3.0
standard deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 2.0


In [8]:
# combining array

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.vstack((a, b))
d = np.hstack((a,b))
e = np.concatenate((a,b))
print(e)
print(d)
print(c)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [7]:
np.random.randint(1,9, size=(2,3))

array([[7, 5, 6],
       [7, 6, 8]], dtype=int32)