In [2]:
## Numpy
import numpy as np
a=np.array([1,2,3,4,5])

In [5]:
a.shape
a.reshape(5,1)
print(type(a))

<class 'numpy.ndarray'>


In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array', arr)
print('Array type', arr.dtype)
print(arr[0][0])
print(arr[1:,2:])

Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array type int64
1
[[6]
 [9]]


In [18]:
import pandas as pd

In [20]:
## pandas
## series dataframe
data=[23,45,67]
index=['a','b','c']
series=pd.Series(data,index)
print(series)
print(type(series))

a    23
b    45
c    67
dtype: int64
<class 'pandas.core.series.Series'>


In [22]:
## Dataframe
data = {
     'Name': ['Ankit', 'Krish'],
     'Age': [20, 35],
     'City': ['jabalpur', 'delhi']
}
df=pd.DataFrame(data)
print(df)

    Name  Age      City
0  Ankit   20  jabalpur
1  Krish   35     delhi


In [26]:
print("loc value: ",df.loc[0])
print("iloc value: ",df.iloc[0])

loc value:  Name       Ankit
Age           20
City    jabalpur
Name: 0, dtype: object
iloc value:  Name       Ankit
Age           20
City    jabalpur
Name: 0, dtype: object
